# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FGsM4HGpWQWvGrF41MzMncUl6/c6OgrDnEgXC5aE9LRwaLSqaMiy3dSFHdJccmGaqQQjP9iF7lxNyQx1uDFpiZAXitwrBDMZGgd8Ov8wEalaEpYbueI2SO7SJ2tuIb3OL/hOvzeyEh6NNK/tKxDfzxGmvQokoIcO3nctH2UWyWLhsAm6h5wIKnTuyC7ucC/eiA1Td7qdMUPMNuM4zLJUeAUzIoAZWbBSZs5aLIV+eWeFMBR7LL9MenElz4rrXPyb2npg45nu1hVZFi2VgrqVaHM7pdD9AF6P71LwRKNN/FUJiWIv0m4c05M7G6scvBN2PaJrvEG2eZ1ww/lvSUSVfigLktzeiCqIHGT9Q2w53E5A6HzIJ/gih3GosK3nS1UuT81OiJd6Jd9bH9V/eAQeRw8M/OTTVEMkTHqUZyzOtdcAOYE4VSIMvFD/ueg7CgYbyNyliewDnRJPFk8WYczkT08j1/VsID9zXrwh4dJblKUHC6Rsmm+YE5RYekxChxMM8d5r52+vViMQTkvDjX8snd2jK40Yp5dvzYawWx54orePKjigEm2qX7KILikqGrzTlvSiombVO2160RwwIJugfiCt76YDugYudA+QvbTQnApngF9QHl4/cemnr2koPpAAOPPoEe+SdM6YbHzj2kAdj7ewRHusebyh2OKqTH3m/8M="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
