appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FGsM4HGpWQWvGrF41MzMncUl6/c6OgrDnEgXC5aE9LRwaLSqaMiy3dSFHdJccmGaqQQjP9iF7lxNyQx1uDFpiZAXitwrBDMZGgd8Ov8wEalaEpYbueI2SO7SJ2tuIb3OL/hOvzeyEh6NNK/tKxDfzxGmvQokoIcO3nctH2UWyWLhsAm6h5wIKnTuyC7ucC/eiA1Td7qdMUPMNuM4zLJUeAUzIoAZWbBSZs5aLIV+eWeFMBR7LL9MenElz4rrXPyb2npg45nu1hVZFi2VgrqVaHM7pdD9AF6P71LwRKNN/FUJiWIv0m4c05M7G6scvBN2PaJrvEG2eZ1ww/lvSUSVfigLktzeiCqIHGT9Q2w53E5A6HzIJ/gih3GosK3nS1UuT81OiJd6Jd9bH9V/eAQeRw8M/OTTVEMkTHqUZyzOtdcAOYE4VSIMvFD/ueg7CgYbyNyliewDnRJPFk8WYczkT08j1/VsID9zXrwh4dJblKUHC6Rsmm+YE5RYekxChxMM8d5r52+vViMQTkvDjX8snd2jK40Yp5dvzYawWx54orePKjigEm2qX7KILikqGrzTlvSiombVO2160RwwIJugfiCt76YDugYudA+QvbTQnApngF9QHl4/cemnr2koPpAAOPPoEe+SdM6YbHzj2kAdj7ewRHusebyh2OKqTH3m/8M=}
