travis:
  secure:
    BINSTAR_TOKEN: WmufpBsr5AmTMvyw89nTiuSsFkXiIK/71LAyE9gZMy87k5pT+7H62xMKolkm9X9kpk7yJK4LYK8pbLCLQ1jKvuBBQdPvSi8WwbcoUoTUgj4gttnFw0Z+JA4f7YiwAW5mWGUNuWDojeWBoT2JlSoX1UuTxQ/mxNT1iGJxCwgoYyLJooIJaZMM8tATF6CNzQO6poarrG1nuGprGhN1c4mQZ5Zwa+aUZuT36P8dQraPLXeDKn1FKwKWoaklJKumWgBHw8O+6i+2r7Nlr09YYWPESRuZw6z0JuFRf9Fwb3PBEsMjIYN4O2mn63+h9Oc85kn5+VRIGoHHJfYjXYqfA96lw95772DJPNBxRgJOV67ow0QFm13MQKP4K51ACAGMuILZGd6onG0SMSYFzVpeS9G5PNK6TOMkcoJASexSGDQst7FZq0f6VB8dl/nKUhoCd8uO9gNe4Izaao9kTLgT+2/o+Kr/uOWc+9G2w7Yvn78ckNt9gDoGiTzhJD8BYpeJiastpkJTsJpRb4qvcxQiOJTJlEv1wmWVWhs5Ur1Y0sJp3tYH7L/38uQ0ojmUukAEs6vKpObmXFaJuPf0l9Y6YQRCPAbbFy8Y+Fjleg1FYaqO88cfmpzs8mKYB+RduPARM4gTWJBKsEn6WiP8X1pDahhonI4OCIOaWmL7zVwX3h4pqJE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
